version: '3'

tasks:
  create-task:
    silent: true
    dir: "{{ .CLI_ARGS }}"
    cmds:
      - go mod init github.com/iainvm/AdventOfCode/{{ .CLI_ARGS }}
      - touch main.go

  run-task:
    silent: true
    dir: "{{ .CLI_ARGS }}"
    cmds:
      - go run .
